# Database Configuration
spring:
  banner:
    location: banner.txt
  data:
    mongodb:
      database: Field_db
      host: localhost
      password: 123456
      port: 27017
      username: arslan

# Server Configuration
server:
  port: 8081

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
    appname: field-core-services
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true: