# Database Configuration
spring:
  banner:
    location: banner.txt
  data:
    mongodb:
      database: Field_db
      host: localhost
      password: 123456
      port: 27017
      username: arslan
  pulsar:
    client:
      service-url: pulsar://localhost:6650

# Server Configuration
server:
  port: 8081

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
    appname: field-services
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true:

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true

openapi:
  service:
    title: field-services
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /field-services/v3/api-docs
  swagger-ui:
    path: /field-services/swagger-ui.html