version: '3.9'

services:

  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
  pulsar:
    image: "apachepulsar/pulsar:latest"
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - ./pulsar/data:/pulsar/data
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: unless-stopped