version: '3.9'

services:

  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
  pulsar:
    container_name: pulsar
    command: 'bin/pulsar standalone'
    image: 'apachepulsar/pulsar:3.1.1'
    ports:
      - '8010:8080'
      - '6650:6650'
    tty: true
    stdin_open: true