# Database configuration
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: Field_db
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/Field_db

# Server configuration
server:
    port: 8083


# eureka configuration
eureka:
  instance:
    hostname: localhost
    appname: job-service
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true: