# Database configuration
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: Field_db
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/Field_db

# Server configuration
server:
    port: 8083


# eureka configuration
eureka:
  instance:
    hostname: localhost
    appname: job-services
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true

  output:
    ansi:
      enabled: always

openapi:
  service:
    title: job-services
    version: 1.0.0
    url: http://localhost:8083
springdoc:
  api-docs:
    path: /job-services/v3/api-docs
  swagger-ui:
    path: /job-services/swagger-ui.html
