app:
  jwt:
    get:
      token:
        uri: /authenticate
    secret: springbootjwtsecret
    token:
      validity: 3600
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  banner:
    location: banner.txt
  data:
    mongodb:
      database: Field_db
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/Field_db
server:
    port: 8083
eureka:
  instance:
    hostname: localhost
    appname: job-service
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true: