server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    appname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 1000


#  http://localhost:8761/eureka
