
app:
  jwt:
    get:
      token:
        uri: /authenticate
    secret: springbootjwtsecret
    token:
      validity: 3600
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  banner:
    location: banner.txt
  data:
    mongodb:
      database: Field_db
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/Field_db

server:
  port: 8082
eureka:
  instance:
    hostname: localhost
    appname: idm-services
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true:

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true

openapi:
  service:
    title: idm-services
    version: 1.0.0
    url: http://localhost:8082
springdoc:
  api-docs:
    path: /idm-services/v3/api-docs
  swagger-ui:
    path: /idm-services/swagger-ui.html

pulsar:
  connection:
    url: pulsar://localhost:6650
    topic: permission-topic
    consumer-name: permission_sender
user:
  management:
    enable: false