server:
  port: 8084

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArslanKucukkafa/spring-config-server.git
          clone-on-start: true
