# Token Creditentials
app:
  jwt:
    secret: springbootjwtsecret

# Eureka Configuration
eureka:
  instance:
    hostname: localhost
    appname: gateway-service
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled=true:

spring:
  application:
    name: gateway-services
  cloud:
    gateway:
      routes:
        - id: idm-services
          uri: http://localhost:8082
          predicates:
                - Path=/idm/**
        - id: fieldcore-services
          uri: http://localhost:8081
          predicates:
                - Path=/field/**
        - id: job-services
          uri: http://localhost:8083
          predicates:
                - Path=/job/**
